### ISSUE TITLE
gns_connect keeps failing

### ISSUE THREAD

**Issue by kbavishi** [ayadavumass/Downloads#1]
Hi,

I've been trying to use the GNS CLI to create an account, but I can't get ```gns_connect``` to pass in the latest version (1.16_2015-11-12_build262). Here's what the console output looks like. (See the ```<<<``` marker)
```bash
% java -jar gns-cli-1.16-2015-11-12.jar
GNS Client Version: 1.16_2015-11-12_build262
Default GNS: null
GNS CLI - not connected to GNS>gns_connect gnserve.net 24398 true
Nov 21, 2015 2:31:19 AM edu.umass.cs.nio.NIOTransport finishConnection
INFO: Node null failed to (re-)connect to gnserve.net/54.241.21.88:24398:Connection refused  <<<
Checking GNS connectivity.
Failed to connect to GNS ( java.io.IOException: +TIMEOUT+)
GNS CLI - not connected to GNS>
```
Note that I get a big stack trace if I don't disable SSL. See the output below:
```
GNS CLI - not connected to GNS>gns_connect gnserve.net 24398
Nov 21, 2015 2:35:27 AM edu.umass.cs.utils.Config register
WARNING: Config unable to find file gigapaxos.properties; using default values for type class edu.umass.cs.gigapaxos.PaxosConfig$PC
Nov 21, 2015 2:35:27 AM edu.umass.cs.utils.Config register
WARNING: Config unable to find file gigapaxos.properties; using default values for type class edu.umass.cs.gigapaxos.PaxosConfig$PC
Nov 21, 2015 2:35:27 AM edu.umass.cs.utils.Config register
WARNING: Config unable to find file gigapaxos.properties; using default values for type class edu.umass.cs.reconfiguration.ReconfigurationConfig$RC
Nov 21, 2015 2:35:27 AM edu.umass.cs.nio.SSLDataProcessingWorker register
INFO: SSLDataProcessingWorker0.0.0.0/0.0.0.0:0 registered client socket channel java.nio.channels.SocketChannel[connected local=/172.20.58.5:52373 remote=gnserve.net/54.241.21.88:24
498]
javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
        at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1214)
... (snipped)
``` 
I don't see these problems with the previous version (1.5_2014-1-7_build1) I used. Is this supposed to be fixed by the gigapaxos [commit](https://github.com/MobilityFirst/GNS/commit/8213cbd5aff2a2b8386029096e45c6730b84afb7) made by westyUMass?

**Comment by kbavishi** [comment]
Actually I pulled in a fresh copy of the GNS repo, and tried out the gns-cli after building, but the issue remained. It seems the like the gigapaxos commit doesn't fix the problem above

**Comment by ayadavumass** [comment]
Hi Karan,
First of all thanks for testing out our system. One thing I would say is commenting here is good, but also just send an email to support@gns.name so that it goes to the person who directly manages these things. 
Now gnserve.net is running with SSL enabled and I have been told this by Westy who managed this
"SSL requires a keystore and truststore to be specified. See/Use the script in
scripts/client/runCLI" 

I myself haven't had time to test it yet but he says it should work like that. I will let you know when I test it out. In the meantime you can go ahead and check if it works, if it doesn't then please  send an email to support@gns.name and also mention the problem here

**Comment by kbavishi** [comment]
Thanks for the help Aditya. Using the "runCLI" script did solve the problem. I will mark the issue as closed, and will raise any further issues with support@gns.name
